"""initial

Revision ID: 37510c9529eb
Revises: 
Create Date: 2022-11-18 15:18:40.341621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37510c9529eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Status',
    sa.Column('idStatus', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idStatus')
    )
    op.create_table('User',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=45), nullable=True),
    sa.Column('FirstName', sa.String(length=45), nullable=False),
    sa.Column('LastName', sa.String(length=45), nullable=False),
    sa.Column('Email', sa.String(length=45), nullable=True),
    sa.Column('Password', sa.String(length=300), nullable=False),
    sa.Column('Phone', sa.String(length=45), nullable=False),
    sa.Column('Role', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('UserName')
    )
    op.create_table('Drug',
    sa.Column('idDrug', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('idStatus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idStatus'], ['Status.idStatus'], ),
    sa.PrimaryKeyConstraint('idDrug')
    )
    op.create_table('Order',
    sa.Column('idOrder', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('idStatus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idStatus'], ['Status.idStatus'], ),
    sa.ForeignKeyConstraint(['idUser'], ['User.idUser'], ),
    sa.PrimaryKeyConstraint('idOrder')
    )
    op.create_table('OrderDetails',
    sa.Column('idOrderDetails', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idOrder', sa.Integer(), nullable=False),
    sa.Column('idDrug', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idDrug'], ['Drug.idDrug'], ),
    sa.ForeignKeyConstraint(['idOrder'], ['Order.idOrder'], ),
    sa.PrimaryKeyConstraint('idOrderDetails')
    )
    op.drop_index('Email', table_name='user')
    op.drop_index('UserName', table_name='user')
    op.drop_table('user')
    op.drop_table('orderdetails')
    op.drop_table('drug')
    op.drop_table('status')
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('idOrder', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idUser', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idStatus', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idStatus'], ['status.idStatus'], name='order_ibfk_1'),
    sa.ForeignKeyConstraint(['idUser'], ['user.idUser'], name='order_ibfk_2'),
    sa.PrimaryKeyConstraint('idOrder'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('status',
    sa.Column('idStatus', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idStatus'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('drug',
    sa.Column('idDrug', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('Price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idStatus', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idStatus'], ['status.idStatus'], name='drug_ibfk_1'),
    sa.PrimaryKeyConstraint('idDrug'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orderdetails',
    sa.Column('idOrder', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idDrug', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idDrug'], ['drug.idDrug'], name='orderdetails_ibfk_1'),
    sa.ForeignKeyConstraint(['idOrder'], ['order.idOrder'], name='orderdetails_ibfk_2'),
    sa.PrimaryKeyConstraint('idOrder'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('idUser', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserName', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('FirstName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('LastName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('Phone', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('Role', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idUser'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('UserName', 'user', ['UserName'], unique=False)
    op.create_index('Email', 'user', ['Email'], unique=False)
    op.drop_table('OrderDetails')
    op.drop_table('Order')
    op.drop_table('Drug')
    op.drop_table('User')
    op.drop_table('Status')
    # ### end Alembic commands ###
